likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

mainapp/urls.py
from django.urls import path

from mainapp.views import BasicTemplateView

app_name = 'mainapp'

urlpatterns = [
    path('mainpage/', BasicTemplateView.as_view(), name='mainpage'),
]

traceapp/urls.py
from django.urls import path

from traceapp.views import BasicTemplateView

app_name = 'traceapp'

urlpatterns = [
    path('group/', BasicTemplateView.as_view(), name='group'),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import TemplateView
import requests
import json
import pandas as pd
import os
import numpy as np
from selenium import webdriver
from bs4 import BeautifulSoup as soup
import time
import datetime

cwd = os.getcwd()

def News_category():
    today = datetime.datetime.now()
    yesterday = today - datetime.timedelta(1)
    yesterday = yesterday.strftime("%Y%m%d")

    t = time.time()
    today = time.strftime("%Y-%m-%d", time.gmtime(t))

    yesterday = yesterday[:4] + '-' + yesterday[4:6] + '-' + yesterday[6:]
    date1 = str(int(yesterday[:4] + yesterday[5:7] + yesterday[8:]) - 1)
    category = ["정치", "경제", "사회", "국제", "문화", "스포츠", "IT_과학",""]
    per_res = {}



    my_key = "a19a4199-9fe3-4dff-90ed-6512bb359f2b"

    result_url = 'http://tools.kinds.or.kr:8888/search/news'
    for i in range(len(category)):
        data = {
            "access_key": f"{my_key}",
            "argument": {
                "query": "",
                "published_at": {
                    "from": yesterday,
                    "until": today
                },
                "provider": [""],
                "category": [category[i]],
                "provider_subject": [""],
                "subject_info": [""],
                "sort": {
                    "date": "desc"
                },
                "hilight": 200, "return_from": 0, "return_size": 20000,
                "fields": [
                    "hilight","category","category_incident","images","provider_subject","subject_info",
                    "provider_news_id","publisher_code"
                ]
            }
        }

        response = requests.post(result_url, data=json.dumps(data))
        res_json = response.json()
        res_doc = res_json['return_object']['documents']
        res_title = [x['title'] for x in res_doc]

        sen_res = []

        for sen in res_title:
            if '“' in sen:
                sen = sen.replace('“', '"')
                if '”' in sen:
                    sen = sen.replace('”', '"')
                sen_res.append(sen)
            elif '”' in sen:
                sen = sen.replace('”', '"')
                sen_res.append(sen)
            elif '"' in sen:
                sen_res.append(sen)
        per = len(sen_res) / len(res_title)

        per_res[category[i]]=str(np.round((per*100),1))+'%'
        # print("{} {} 뉴스에 {}%의 비율로 따옴표가 쓰였습니다.".format(today, category[i], np.round(per * 100, 2)))

    politics = per_res['정치']
    economy = per_res['경제']
    social = per_res['사회']
    world = per_res['국제']
    culture = per_res['문화']
    sports = per_res['스포츠']
    science = per_res['IT_과학']
    total = per_res['']
    return [politics,economy,social,world,culture,sports,science,total,yesterday]

def search_selenium(search_name):
    search_url = "https://www.google.com/search?q=" + str(search_name) + "&hl=ko&tbm=isch"
    options = webdriver.ChromeOptions()
    # 창 숨기는 옵션 추가
    options.add_argument("headless")
    browser = webdriver.Chrome("C:\\Users\\JH\\Downloads\\chromedriver_win32\\chromedriver.exe",options=options)
    # soup = BeautifulSoup(text, 'html.parser')
    browser.get(search_url)
    # img = soup.find("img")
    # img_src = img.get("src")

    browser.implicitly_wait(2)
    image = browser.find_elements_by_tag_name("img")[0]
    image.screenshot(cwd + '\\static\\img\\top.jpg')
    image_loc = (cwd + '\\static\\img\\top.jpg')
    browser.quit()
    return image_loc

def weekly_keyword():
    t = time.time()
    today = time.strftime("%Y-%m-%d", time.gmtime(t))
    date1 = str(int(today[:4]+today[5:7]+today[8:]) - 7)
    lastday = date1[:4] + '-' + date1[4:6] + '-' + date1[6:]
    date = today[:4]+'년'+today[5:7]+'월'+today[8:]+'일'
    my_key = "a19a4199-9fe3-4dff-90ed-6512bb359f2b"

    result_url = 'http://tools.kinds.or.kr:8888/search/news'

    data = {
        "access_key": f"{my_key}",
        "argument": {
            "query": "",
            "published_at": {
                "from": lastday,
                "until": today
            },
            "provider": [""],
            "category": [""],
            "category_incident": [""],
            "provider_subject": [""],
            "subject_info": [""],
            "sort": {"date": "desc"},
            "hilight": 200,
            "return_from": 0,
            "return_size": 20000,
            "fields": ["hilight", "category", "category_incident", "images", "provider_subject",
                       "subject_info", "provider_news_id", "publisher_code"]}
    }

    response = requests.post(result_url, data=json.dumps(data))
    res_json = response.json()
    res_doc = res_json['return_object']['documents']
    res_title = [x['title'] for x in res_doc]

    sen_res = []

    for sen in res_title:
        if '“' in sen:
            sen = sen.replace('“', '"')
            if '”' in sen:
                sen = sen.replace('”', '"')
            sen_res.append(sen)
        elif '”' in sen:
            sen = sen.replace('”', '"')
            sen_res.append(sen)
        elif '"' in sen:
            sen_res.append(sen)

    res_fin = []
    for i in range(len(sen_res)):
        if sen_res[i].count('"') == 1:
            sen_fin = sen_res[i].replace('"', ' ')
            res_fin.append(sen_fin)
        else:
            begin = sen_res[i].index('"')
            if '"' in sen_res[i][begin + 1:]:
                end = sen_res[i][begin + 1:].index('"')
            else:
                end = begin

            sen = sen_res[i].replace(sen_res[i][begin:begin + end + 2], ' ')
            if '"' in sen:
                second = sen.index('"')
                if '"' in sen[second + 1:]:
                    second_end = sen[second + 1:].index('"')
                else:
                    second_end = second
                sen_fin = sen.replace(sen[second:second + second_end + 2], ' ')
                res_fin.append(sen_fin)
            else:
                res_fin.append(sen)

    words = []
    props = [',', '.', '"', '?', '…', '+', '[', ']', 'vs', '‘', '’', '  ', '   ', '    ', '     ']
    for sen in res_fin:
        for prop in props:
            sen = sen.replace(prop, " ")
        sen = sen.split(" ")
        for word in sen:
            words.append(word)

    word_cnt = []
    for word in words:
        cnt = words.count(word)
        word_cnt.append((cnt, word))

    se = set(word_cnt)
    fin = list(se)

    word_list = []
    num_list = []
    for i in range(len(fin)):
        word_list.append(fin[i][1])
        num_list.append(fin[i][0])

    for j in range(1, len(word_list)):
        for i in range(j + 1, len(word_list)):
            if word_list[j] in word_list[i]:
                num_list[j] += 1
    final = []
    for i in range(len(word_list)):
        if len(word_list[i]) > 1:
            final.append([num_list[i], word_list[i]])
    final.sort(reverse=True)
    top = final[0][1]
    im_loc = search_selenium(top)

    return [top,im_loc,date]

class BasicTemplateView(TemplateView):
    template_name = 'mainapp/base.html'



    def get(self, request, *args, **kwargs):
        # kwargs['test'] = News_data()[0]
        # kwargs['date'] = News_data()[1]
        kwargs['politics'] = News_category()[0]
        kwargs['economy'] = News_category()[1]
        kwargs['social'] = News_category()[2]
        kwargs['world'] = News_category()[3]
        kwargs['culture'] = News_category()[4]
        kwargs['sports'] = News_category()[5]
        kwargs['science'] = News_category()[6]
        kwargs['total'] = News_category()[7]

        kwargs['top'] = weekly_keyword()[0]
        kwargs['image_loc'] = weekly_keyword()[1]
        kwargs['today'] = weekly_keyword()[2]
        return super().get(request, *args, **kwargs)

mainapp/templates/mainapp/base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col mx-2" style="background-color: #FFE16B; height:50rem; border:4px solid #0a0a0a; border-radius: 1rem">

            <div class="text-center">
                <br>
                <div style="font-size: 3rem; font-family: 'Gowun Dodum', sans-serif;">SCORE BOARD</div>
                <br>
            </div>
            {# 달력 #}
            <h4 class="text-center" style="padding-right:1rem;">
                <a style="font-size: 1.8vw; ">
                    {{ today }}
                </a>
            </h4>

            {# 따옴표지수 #}
            <div class="col my-2" style="font-family: 'Gowun Dodum', sans-serif; border: 3px solid #0a0a0a; background-color:#EDE8D3; height:13rem; border-radius:1rem">
                <div class="text-left" style="padding-left:1rem;">
                    <a style="font-size: 1.8vw; ">
                        오늘의 따옴표 지수&nbsp&nbsp
                    </a>
                    <a style="font-size: 1.2vw;">
                        {{ today }}
                    </a>
                </div>
                <div class="text-center" style="padding:1.5rem; font-size:3rem;">
                    {{ total }}
                </div>
            </div>
            {# 토픽별 따옴표 지수 #}
            <div class="col my-2" style="font-family: 'Gowun Dodum', sans-serif; border: 3px solid #0a0a0a; background-color:#EDE8D3; height:22rem; border-radius:1rem">
                <div class="text-left" style="padding-left:1rem;">
                    <a style="font-size: 1.6vw; ">
                       카테고리별 따옴표 지수&nbsp&nbsp
                    </a>
                    <a style="font-size: 1vw;">
                        {{ today }}
                    </a>
                </div>
                <div class="row" style="margin-top:3.5rem">
                    <div class="col text-center" style="border-right: 3px solid #0a0a0a;">
                        정치: {{ politics }}
                    </div>
                    <div class="col text-center">
                        국제: {{ world }}
                    </div>
                </div>
                <div class="row" style="margin-top:1.2rem">
                    <div class="col text-center" style="border-right: 3px solid #0a0a0a;">
                        경제: {{ economy }}
                    </div>
                    <div class="col text-center">
                        사회: {{ social }}
                    </div>
                </div>
                <div class="row" style="margin-top:1rem">
                    <div class="col text-center" style="border-right: 3px solid #0a0a0a;">
                        스포츠: {{ sports }}
                    </div>
                    <div class="col text-center">
                        문화: {{ culture }}
                    </div>
                </div>
                <div class="row" style="margin-top:1rem">
                    <div class="col text-center" style="border-right: 3px solid #0a0a0a;">
                        &nbsp&nbsp&nbspIT_과학: {{ science }}
                    </div>
                    <div class="col text-center">

                    </div>
                </div>
            </div>

        </div>

        <div class="col mx-2" style="background-color: #FFE16B; height:50rem; border:4px solid #0a0a0a; border-radius: 1rem">
            <h5 class="text-center" style="margin-top:1rem; font-family: 'Gowun Dodum', sans-serif;">< Today's 판단유보(A유형) ></h5>
            <div class="col my-2" style="border: 3px solid #0a0a0a; background-color:#EDE8D3; height:13rem; border-radius:1rem">
                 <span class="mx-2">
                    <a href="{% url 'traceapp:group' %}">
                        해부!따옴표!
                    </a>
                 </span>
                <p>검찰 "수사팀 불찰 송구...경찰 분석에 적극 협력"</p>
                <p>국감 나온 남양유업 회장 "바지사장" 질타에 "몰랐다"</p>
                <p>카카오모빌리티 "스마트호출 이어 프로멤버십도 폐지 검토"</p>
            </div>

            <h5 class="text-center" style="margin-top:1rem; font-family: 'Gowun Dodum', sans-serif;">< Today's 책임회피(B유형) ></h5>
            <div class="col my-2" style="border: 3px solid #0a0a0a; background-color:#EDE8D3; height:13rem; border-radius:1rem">
                 <span class="mx-2">
                    <a href="{% url 'traceapp:group' %}">
                        해부!따옴표!
                    </a>
                 </span>
                <p>북한군 피격 공무원 유족 "직접 챙기겠다는 대통령 약속 잊었나"</p>
                <p>與, 최재형 탈락에 맹비난...원희룡 "사과하라"</p>
                <p>與 정청래, 최재형에 "다시는 정치권 기웃 말라"</p>
            </div>
            <h5 class="text-center" style="margin-top:1rem; font-family: 'Gowun Dodum', sans-serif;">< Today's 선정성(C유형) ></h5>
            <div class="col my-2" style="border: 3px solid #0a0a0a; background-color:#EDE8D3; height:13rem; border-radius:1rem">
                 <span class="mx-2">
                    <a href="{% url 'traceapp:group' %}">
                        해부!따옴표!
                    </a>
                 </span>
                <p>한국어로 "무궁화 꽃이 피었습니다"···경찰까지 딱 멈춘 여긴···</p>
                <p>국힘 4강 승자는 '화천대유 1타강사' 원희룡… "이재명 민낯 드러낼 것"</p>
                <p>홍수 피해 입었지만 대박 난 태국 식당 "물 튀어도 좋아"</p>
            </div>
        </div>

        <div class="col mx-2" style="height: 50rem;">

            <div class="row my-2" style="background-color: #FFE16B; height:24rem; border:4px solid #0a0a0a; border-radius: 1rem;">
                <div class="text-center" style="font-size:1.3rem; margin-top:1rem; font-family: 'Gowun Dodum', sans-serif;">
                    따옴표 유형을 분석해보세요!
                    <nav class="navbar navbar-expand-lg">
                      <div class="container-fluid">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                          <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="주소를 입력해주세요." aria-label="Search" style="width:15rem" aria-current="true">
                            <button class="btn btn-outline-success" type="submit">
                                <a href="{% url 'mainapp:mainpage' %}" >
                                    분석 ✔
                                </a>
                            </button>
                          </form>
                        </div>
                      </div>
                    </nav>
                </div>
                <div class="col my-2" style="background-color: #EDE8D3; border-top: 4px solid #0a0a0a; width:1rem; height:16.65rem; border-bottom-left-radius:0.6rem; border-bottom-right-radius:0.6rem">
                    <div style="margin-top:1rem; font-family: 'Gowun Dodum', sans-serif;" class="text-center">
                        <div style="font-size:1.5rem;">
                            < &nbsp;유형 분석 결과&nbsp; >
                        </div>
                        <div style="background-color: #a2d7c7">
                        <br>"화이자 접종 후 사경 헤매"...백신 부작용 청원 잇따라
                        </div>
                    </div>
                    <div class="mb-2" style="font-family: 'Gowun Dodum', sans-serif;">
                        <br>
                        <span data-view-component="true"     style="display: flex; height: 1.3rem; overflow-x: hidden;
                        overflow-y: hidden; border-radius:6px; outline-color: transparent; outline-style: solid; outline-width: 1px;">
                            <span style="background-color:#3572A5 !important;;width: 11.2%;" itemprop="keywords" aria-label="A유형" data-view-component="true" class="Progress-item color-bg-success-inverse">
                                <div class="text-center" style="font-size:0.8rem; color:white">
                                    A유형
                                </div>
                            </span>
                            <span style="background-color:#e34c26 !important;;width: 71.5%;" itemprop="keywords" aria-label="B유형" data-view-component="true" class="Progress-item color-bg-success-inverse">
                                <div class="text-center" style="font-size:0.8rem; color:white">
                                    B유형
                                </div>
                            </span>
                            <span style="background-color:#f1e05a !important;;width: 17.3%;" itemprop="keywords" aria-label="C유형" data-view-component="true" class="Progress-item color-bg-success-inverse">
                                <div class="text-center" style="font-size:0.8rem; color:white">
                                    C유형
                                </div>
                            </span>
                        </span>
                    </div>
                    <div style="margin-top:0.3rem; font-family: 'Gowun Dodum', sans-serif;">
                        <div class="text-center">
                            A유형 11.2%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; B유형 71.5%&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; C유형 17.3%<br><br>
                            ⇒&nbsp;&nbsp; 본 기사는 '책임회피(B유형)' 에 해당됩니다.
                        </div>
                    </div>
                </div>
            </div>

            <div class="row my-2" style="height: 0.3rem;"></div>

            <div class="row my-2" style="background-color: #FFE16B; height: 24rem; border:4px solid #0a0a0a; border-radius: 1rem">
                <div class="text-center" style="margin-right:5rem; font-size: 2.5rem; font-family: 'Gowun Dodum', sans-serif;">
                    WINNER&nbsp; BOARD
                </div>
                <div class="text-center" style="font-family: 'Gowun Dodum', sans-serif;">
                    <a style="font-size:1.2rem">
                        이 주의 따옴표 주인공은
                    </a>
                    <a style="font-size:1.6rem">
                        <br>{{ top }}
                    </a>
                    <a style="font-size:1.2rem">
                        입니다.
                    </a>
                </div>
                <div class="mx-2">
                    <div class="col" style="background-color: #EDE8D3; width:23rem; height: 13rem; border:3px solid #0a0a0a; border-radius: 1rem">
                        <img src="{% static 'img/top.jpg' %}"
                             style="width: 100%;
                                    height: 100%;
                                    border-radius: 1rem;
                                    object-fit: cover;"
                         >
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}