accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'





urlpatterns = [

    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

contactapp/urls.py
from django.urls import path

from contactapp.views import BasicTemplateView

app_name = 'contactapp'

urlpatterns = [
    path('introduce/', BasicTemplateView.as_view(), name='introduce'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

mainapp/urls.py
from django.urls import path

from mainapp.views import BasicTemplateView

app_name = 'mainapp'

urlpatterns = [
    path('mainpage/', BasicTemplateView.as_view(), name='mainpage'),
]

replaceapp/urls.py
from django.urls import path

from replaceapp.views import BasicTemplateView, let_write

app_name = 'replaceapp'

urlpatterns = [
    path('challenge/', BasicTemplateView.as_view(), name='challenge'),
    path('let_write/', let_write, name='let_write'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body class="body" style="font-family: 'NanumSquareR';">

{% include 'header.html' %}

<hr>

{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}


</body>
</html>

templates/footer.html
<div style="text-align: center">

    <div class="pragmatic_footer_button">
        <span class="mx-1">
            <a href="{% url 'contactapp:introduce' %}">
                TEAM 66.99
            </a>
        </span>
        <span class="mx-1">
            <a href="https://www.bigkinds.or.kr/">
                <br>2021 NEWS BIGDATA HACKATHON
            </a>
        </span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>66.99</h5>
    </div>

</div>

templates/head.html
<!DOCTYPE html>
<html lang="en">
{%  load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    {#  BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  Google font LINK1 #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    {# Google font LINK2-DoHyun #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    {# Google font LINK3-GowunDodum #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">

    {# DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {# MATERIAL ICONS LINK #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">
    <div class="pragmatic_header_logo">
        <a href="{% url 'analysisapp:explain' %}">
            66.99
        </a>
    </div>
    <div class="pragmatic_header_button">

        <span class="mx-2">
            <a href="{% url 'analysisapp:explain' %}">
                분석!따옴표!
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'mainapp:mainpage' %}">
                추적!따옴표!
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'replaceapp:challenge' %}">
                대체!따옴표!
            </a>
        </span>
        {% if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accountapp:login' %}">
                로그인
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:create' %}">
                회원가입
            </a>
        </span>
        {% else %}
        <span class="mx-2">
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                Mypage
            </a>
        </span>
            <span class="mx-2">
            <a href="{% url 'accountapp:logout' %}">
                로그아웃
            </a>
        </span>
        {% endif %}
    </div>
</div>